# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy
run-name: Deployment of ${{ inputs.commit }} to ${{ inputs.environment }} by @${{ github.actor }}
on:
    workflow_dispatch:
        inputs:
            commit:
                description: SHA-1 commit hash
                type: string
                required: true
            environment:
                description: Deployment environment
                type: environment
                required: true
concurrency:
    group: ${{ inputs.environment }}
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_NOLOGO: true
jobs:
    check-environment:
        environment:
            name: ${{ inputs.environment }}
            url: https://${{ (inputs.environment == 'staging' && 'staging.') || '' }}tera-arise.io
        runs-on: ubuntu-22.04
        steps:
            - run: ''
    deploy-client:
        # For deployments to staging, it is expected that people build the
        # relevant commit locally in order to connect.
        uses: ./.github/workflows/deploy-client.yml
        with:
            commit: ${{ inputs.commit }}
            environment: ${{ inputs.environment }}
        secrets: inherit
    deploy-world:
        needs:
            - deploy-client
        uses: ./.github/workflows/deploy-server.yml
        with:
            commit: ${{ inputs.commit }}
            environment: ${{ inputs.environment }}
            role: world
            fingerprint: ${{ secrets.SSH_WORLD_FINGERPRINT }}
        secrets: inherit
    deploy-web:
        # The launcher queries the web API to get the current release version
        # that it needs to download, so deploy the web server last when
        # everything else is done.
        needs:
            - deploy-client
            - deploy-world
        uses: ./.github/workflows/deploy-server.yml
        with:
            commit: ${{ inputs.commit }}
            environment: ${{ inputs.environment }}
            role: web
            fingerprint: ${{ secrets.SSH_WEB_FINGERPRINT }}
        secrets: inherit
