# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy Client
on:
    workflow_call:
        inputs:
            commit:
                type: string
                required: true
            environment:
                type: string
                required: true
        secrets:
            GH_RELEASE_TOKEN:
                required: true
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_NOLOGO: true
jobs:
    deploy-client:
        if: inputs.environment == 'production'
        runs-on: ubuntu-22.04
        steps:
            - name: Clone repository
              uses: actions/checkout@v3.5.3
              with:
                  ref: ${{ inputs.commit }}
                  fetch-depth: 0
                  submodules: recursive
            - name: Set up .NET
              uses: actions/setup-dotnet@v3.2.0
            - name: Build project
              run: |
                  ./cake -c Release
            - name: Extract build version
              id: version
              run: |
                  echo version=`jq .version out/obj/src/client/switcher/manifest.json -r` >> $GITHUB_OUTPUT
            - name: Zip release
              run: |
                  zip ../../../../../../TERA.Arise.${{ steps.version.outputs.version }}.zip . -r -9
              working-directory: out/pub/src/client/switcher/release_win10-x64
            - name: Upload release
              env:
                  GH_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
              run: |
                  gh release create v${{ steps.version.outputs.version }} manifest.json TERA.Arise.${{ steps.version.outputs.version }}.zip -R tera-arise/arise-release --target cec4115cc94729e4ec89d35efbed418eef207273 --latest
